### Tricia Jonina B. Alcisto

#### problem 1

$$ let $$ $$ u = (1,-2,4)  v = (3,5,1) w = (2,1,-3) $$

$$ a.) 3u-2v $$

$$ 3(1,-2,4) - 2(3,5,1) = (3,-6,12) - (2,10,2) = (-3,-16,10)$$

In [1]:
import numpy as np

In [2]:
u=np.array([1,-2,4])
v=np.array([3,5,1])
print(3*u-2*v)

[ -3 -16  10]


$$ b.) 5u + 3v - 4w $$

$$ 5(1,-2,4)+3(3,5,1)-4(2,1-3)=(5,-10,20)+(9,15,3)-4(8,4,-12)=(6,1,35) $$ 

In [3]:
w=np.array([2,1,-3])
print(5*u+3*v-4*w)

[ 6  1 35]


$$ c.)u.v,v.w,u.w $$

$$ u.v = (1.3)+(-2.5)+(4.1)=3-10+4=-3$$

$$ v.w=(3.2)+(5.1)+(1.(-3)) = 6+5-3=11-3=8 $$

$$ u.w=(1,2)+(-2.1)+(4.(-3))=2-2-12=-12 $$

In [4]:
print("u.v= ", u.dot(v))

u.v=  -3


In [5]:
print("v.w=", v.dot(w))

v.w= 8


In [7]:
print("u.w=", u.dot(w))

u.w= -12


$$ d.)||u||, ||v||, ||w|| $$

$$||u||=\sqrt{u.u} = \sqrt{(1.1)+(-2.-2)+(4.4)} = \sqrt{1+4+16}= \sqrt{21}$$

$$||v||=\sqrt{v.v}=\sqrt{(3.3)+(5.5)+(1.1)}=\sqrt{9+25+1}=\sqrt{35} $$

$$||w||=\sqrt{w.w}=\sqrt{(2.2)+(1.1)+(-3.-3)}=\sqrt{(4+1+9)}=\sqrt{14} $$

In [10]:
print("||u||=",np.sqrt(u.dot(u)))
print("||v||=",np.sqrt(v.dot(v)))
print("||w||=",np.sqrt(w.dot(w)))

||u||= 4.58257569495584
||v||= 5.916079783099616
||w||= 3.7416573867739413


$$e.) if\ \theta \ is \ the \ angle \ between \ u\  and \ v, \ find \cos \theta $$

$$ cos \theta = \frac{u.v}{||u||\||v||}= \frac{(1)^2+(-2)^2+(4)^2}{||u||\||v||} = \frac{-3}{\sqrt{21} \sqrt{35}}$$

In [13]:
print("cos theta: ", u.dot(v)/(np.linalg.norm(u)*np.linalg.norm(v)))

cos theta:  -0.11065666703449763


$$f.)if\ \alpha \ the \ angle \ between \ v\ and \ w, \ find \ cos \alpha $$

$$ cos \alpha = \frac{v.w}{||v|| \ ||w||} = \frac{8}{\sqrt{35} \ \sqrt{14}} $$

>getting v.w from problem c, norm of v and w from problem d

In [14]:
print("cos alpha: ", v.dot(w)/(np.linalg.norm(v)*np.linalg.norm(w)))

cos alpha:  0.36140316116210053


$$g.)if\ \beta \ the \ angle \ between \ u\ and \ w, \ find \ cos \beta $$

$$ cos \beta = \frac{u.w}{||u|| \ ||w||} = \frac{u.w}{||u|| \ ||w||}= \frac{-12}{\sqrt{21}\sqrt{14}} $$

In [16]:
print("cos beta: ", u.dot(w)/(np.linalg.norm(u)*np.linalg.norm(w)))

cos beta:  -0.6998542122237653


$$ h.) find \ d(u,v)$$

$$ d(u,v)=\sqrt{(1-3)^2 + (2-5)^2 + (4-1)^2} = \sqrt{(-2)^2 + (-3)^2 + (3)^2} = \sqrt{4+14+9}= \sqrt{27} $$

In [17]:
print("d(u,v)=", np.linalg.norm(u-v))

d(u,v)= 7.874007874011811


$$ i.) find \ d(w,v)$$

$$ d(w,v)=\sqrt{(2-3)^2 + (1-5)^2 + (-3-1)^2}=\sqrt{(-1)^2 + (-4)^2 + (-4)^2}=\sqrt{1+16+16}=\sqrt{33} $$

In [18]:
print("d(w,v)=", np.linalg.norm(w-v))

d(w,v)= 5.744562646538029


$$ j.)find \ d(u,w) $$

$$ d(u,w)= \sqrt{(1-2)^2 + (-2-1)^2 + (4-(-3))^2} = \sqrt{(-1)^2 + (-3)^2 + 7^2} = \sqrt{1+9+14} = \sqrt{24} $$

In [19]:
print("d(u,w)=", np.linalg.norm(u-w))

d(u,w)= 7.681145747868608


$$ k.)find \ proj(u,v)$$

$$ \frac{u.v}{||v||^2}v= \frac{-3}{35}(3,5,1)= (\frac {-9}{35}, \frac{-15}{35}, \frac{3}{35})=(\frac{-9}{35}, \frac{-3}{7}, \frac{-3}{35})$$

In [20]:
print("proj(u,v)=",u.dot(v)*v/(np.linalg.norm(v)**2))

proj(u,v)= [-0.25714286 -0.42857143 -0.08571429]


$$ l.)find \ proj(w,v) $$

$$proj(w,v)=\frac{w.v}{||v||^2}v= \frac{8}{35}(3,5,1)=(\frac{24}{35}, \frac{40}{35}, \frac{1}{35})=( \frac{24}{35}, 1\frac{1}{7}, \frac{1}{35})$$

In [21]:
print("proj(w,v)=",w.dot(v)*v/(np.linalg.norm(v)**2))

proj(w,v)= [0.68571429 1.14285714 0.22857143]


$$ m.)find \ proj(u,w) $$

$$proj(u,w)= \frac{u.w}{||w||^2}w= \frac{-12}{14}(2,1,3)=(\frac{-24}{14},\frac{-12}{14},\frac{36}{14})=(-1\frac{5}{7},\frac{-6}{7}, 2\frac{4}{7})$$

In [24]:
print("proj(u,w)=",u.dot(w)*w/(np.linalg.norm(w)**2))

proj(u,w)= [-1.71428571 -0.85714286  2.57142857]


#### problem 2

$$ let \ u= \begin{bmatrix} 1\\ 3 \\ -4 \end{bmatrix}, \ v= \begin{bmatrix} 2\\ 1 \\ 5 \end{bmatrix}, \ 
w= \begin{bmatrix} 3\\ -2 \\ 6 \end{bmatrix}$$

$$ a.)3u-2v$$

$$ 3u-2v = 3 \begin{bmatrix} 1\\ 3 \\ -4 \end{bmatrix} - 2 \begin{bmatrix} 3\\ -2 \\ 6 \end{bmatrix} = 
 \begin{bmatrix} 3\\ 9 \\ -12 \end{bmatrix}= \begin{bmatrix} -1\\ 7 \\ -22 \end{bmatrix}$$

In [25]:
u=np.array([1,3,-4])
v=np.array([2,1,5])
w=np.array([3,-2,6])
print(3*u-2*v)

[ -1   7 -22]


$$b.) 5u+3v-4w= 5 $$

$$ 5u+3v-4w= 5 \begin{bmatrix} 1 \\ 3 \\ -4 \end{bmatrix} + 3\begin{bmatrix} 2\\ 1 \\ 5 \end{bmatrix} - 4\begin{bmatrix} 3\\ -2 \\ 6 \end{bmatrix}=
\begin{bmatrix} 5\\ 15 \\ -20 \end{bmatrix} + \begin{bmatrix} 6 \\ 3 \\ 15 \end{bmatrix} - \begin{bmatrix} 12\\ -8 \\ 24 \end{bmatrix} =
\begin{bmatrix} -1\\ 26 \\ -29 \end{bmatrix}$$

In [26]:
print(5*u+3*v-4*w)

[ -1  26 -29]


$$ c.) u.v,v.w,u.w$$

$$ u.v=(1.2) + (3.1) + (-4.5) = 2+3+(-20) = 2+3-20 =-15 $$

$$v.w = (2.3)+(1.(-2))+(5.6)=6+(-2)+(30)=6-2+30=34$$

$$ u.w=(1.3) + (3.(-2)) + (-4.6) = 3+(-6)+(-24)=3-6-24=-27 $$

In [27]:
print("u.v=", u.dot(v))

u.v= -15


In [28]:
print("v.w=", v.dot(w))

v.w= 34


In [29]:
print("u.w=", u.dot(w))

u.w= -27


$$d.) ||u||,||v||,||w||$$

$$||u||=\sqrt{u.u}=\sqrt{(1)^2 + (3)^2 + (-4)^2}= \sqrt{1+9+16} = \sqrt{26} $$

$$||v||= \sqrt{v.v}= \sqrt{(2)^2 + (1)^1 + (5)^2} = \sqrt{4+1+25} = \sqrt{30}$$

$$||w||= \sqrt{w.w}= \sqrt{(3)^2 + (-2)^2 + (6)^2}= \sqrt{9+4+36}= \sqrt{49} \ or \ 7$$

In [30]:
print("||u||=", np.linalg.norm(u))

||u||= 5.0990195135927845


In [32]:
print("||v||=", np.linalg.norm(v))

||v||= 5.477225575051661


In [33]:
print("||w||=",np.linalg.norm(w))

||w||= 7.0


$$e.) if\ \theta \ is \ the \ angle \ between \ u\  and \ v, \ find \cos \theta $$

$$ cos\theta = \frac{u.v}{||u|| \ ||v||} = \frac{-15}{\sqrt{26} \sqrt{30}}$$

In [37]:
print("cos theta =", u.dot(v)/(np.linalg.norm(u)*np.linalg.norm(v)))

cos theta = -0.5370861555295747


$$f.)if\ \alpha \ the \ angle \ between \ v\ and \ w, \ find \ cos \alpha $$

$$cos \alpha = \frac{v.w}{||v|| \ ||w||}=\frac{34}{\sqrt{30} \sqrt{49}} $$

In [38]:
print("cos alpha =", v.dot(w)/(np.linalg.norm(v)*np.linalg.norm(w)))

cos alpha = 0.8867889026274118


$$g.)if\ \beta\ the \ angle \ between \ u\ and \ w, \ find \ cos \beta $$

$$ cos \beta = \frac{u.w}{||u|| \ ||w||} = \frac{-27}{\sqrt{26} \sqrt{49}} $$

In [39]:
print("cos beta =", u.dot(w)/(np.linalg.norm(u)*np.linalg.norm(w)))

cos beta = -0.7564479498187099


$$ h.) find \ d(u,v)$$

$$ d(u,v)= ||u-v||= \sqrt{(1-2)^2 + (3-1)^2 + (-4-5)^2}= \sqrt{(-1)^2 + (2)^2 + (-9)^2}= \sqrt{1,4,81}=\sqrt{86}$$

In [40]:
print("d(u,v)=", np.linalg.norm(u-v))

d(u,v)= 9.273618495495704


$$ i.) find \ d(w,v)$$

$$d(w,v)=||w-v||= \sqrt{(3-2)^2 + (-2-1)^2 + (6-5)^2} = \sqrt{1^2 + -3^2 + 1^2}= \sqrt{1+9+1}= \sqrt{11} $$

In [42]:
print("d(w,v)=", np.linalg.norm(w-v))

d(w,v)= 3.3166247903554


$$ j.) find \ d(u,w)$$

$$ d(u,w)=||u-w||= \sqrt{(1-3)^2 + (3-(-2))^2 + (-4-6)^2}=\sqrt{(-2)^2 + (5)^2 + (-10)^2}=\sqrt{4+25+100}=\sqrt{129}$$

In [43]:
print("d(u,w)=", np.linalg.norm(u-w))

d(u,w)= 11.357816691600547


$$ k.) proj(u,v)$$

$$ proj(u,v) = \frac{u.v}{||v||^2}v= \frac{-15}{30}= \frac{-1}{2} \begin{bmatrix} 2\\ 1 \\ 5 \end{bmatrix} = 
\begin{bmatrix} -1\\ \frac{1}{2} \\ -2 \frac{1}{2} \end{bmatrix}$$

In [44]:
print("proj(u,v)=", u.dot(v)*v/(np.linalg.norm(v)**2))

proj(u,v)= [-1.  -0.5 -2.5]


$$ l.)proj(w,v) $$

$$proj(w,v)= \frac{w.v}{||v||^2}v= \frac{34}{30} \begin{bmatrix} 2\\ 1 \\ 5 \end{bmatrix} = \frac{17}{15} = 1\frac{2}{15}
\begin{bmatrix} 2\\ 1 \\ 5 \end{bmatrix}= \begin{bmatrix} 2 \frac{2}{15} \\ 1\frac{2}{15} \\ 5\frac{2}{15} \end{bmatrix}$$

In [45]:
print("proj(w,v)=", w.dot(v)*v/(np.linalg.norm(v)**2))

proj(w,v)= [2.26666667 1.13333333 5.66666667]


$$m.)proj(u,w) $$

$$ proj(u,w)=\frac{u.w}{||w||^2}w= \frac{-27}{49}\begin{bmatrix} 3\\ -2 \\ 6 \end{bmatrix}=
\begin{bmatrix} \frac{-81}{49} \\ \frac{54}{49} \\ \frac{-162}{49} \end{bmatrix} = 
\begin{bmatrix} -1 \frac{34}{49}\\ 1\frac{5}{49} \\ -3\frac{15}{49} \end{bmatrix} $$

In [47]:
print("proj(u,w)=", u.dot(w)*w/(np.linalg.norm(w)**2))

proj(u,w)= [-1.65306122  1.10204082 -3.30612245]


#### problem 3

$$let \ u=(2, -5,4,6,-3),\ v=(5,-2,1,-7,-4),\ and \ w=(2,1,-3) $$

$$a.) \ 4u-3v $$

$$a.) \ 4u-3v=4u^T-3v^T=4 \begin{bmatrix}2\\ -5 \\ 4 \\ 6 \\ -3 \end{bmatrix}-3\begin{bmatrix}5\\ -2 \\ 1 \\ -7 \\ -4 \end{bmatrix}=
\begin{bmatrix}8\\ -20 \\ 16 \\ 24 \\ -12 \end{bmatrix}-\begin{bmatrix}15\\ -6 \\ 3 \\ -21 \\ -12 \end{bmatrix}=\begin{bmatrix}-7\\ -14 \\ 13 \\ 45 \\ 0 \end{bmatrix}=(-7,14,13,45,0) $$

In [3]:
import numpy as np
u = np.array([2,-5,4,6,-3])
v = np.array([5,-2,1,-7,-4])
w = np.array([2,1,-3])
print("a. 4u-3v: ", (4*u)-(3*v))

a. 4u-3v:  [ -7 -14  13  45   0]


$$5u+2v-2w= \ not \ possible $$

$$c.) \ u \ . \ v = u^T.v^T=\begin{bmatrix}2\\ -5 \\ 4 \\ 6 \\ -3 \end{bmatrix} \ . \ \begin{bmatrix}5\\ -2 \\ 1 \\ -7 \\ -4 \end{bmatrix}= \ \begin{bmatrix}10\\ 10 \\ 4 \\ -42 \\ 12 \end{bmatrix}=-6$$

In [6]:
print(u.dot(v))

-6


$$v \ . \ w= \ not \ possible $$

$$ u.v= \ not \ possible $$

$$d.) \ ||u||= \sqrt{2^2+(-5)^2+4^2+6^2+(-3)^2}=\sqrt{4+25+16+36+9} = \sqrt{90}  $$
$$||v||= \sqrt{5^2+(-2)^2+1^2+(-7)^2+(-4)^2}= \sqrt{95} $$
$$||w||= \sqrt{2^2+1^2+(-3)^2+0^2+0^2}= \sqrt{4+1+9}= \sqrt{14}$$

In [9]:
print("||u||: ", np.linalg.norm(u))
print("||v||: ", np.linalg.norm(v))
print("||w||: ", np.linalg.norm(w))

||u||:  9.486832980505138
||v||:  9.746794344808963
||w||:  3.7416573867739413


$$e.) \ \theta \ is \ the \ angle \ between \ u \ and \ v $$

$$ cos \theta = \frac{u.v}{||u|| \ ||v||} = \frac{-6}{\sqrt{90} \sqrt{95}}$$

In [11]:
print("cos theta: ", (u.dot(v))/(np.linalg.norm(u)*np.linalg.norm(v)))

cos theta:  -0.06488856845230502


$$f.) \ \alpha \ is \ the \ angle \ between \ v \ and \ w$$

$$ cos \alpha=not \ possible $$

$$ g.) \ \beta  \ is \ the \ angle \ between \ v \ and \ w $$

$$ cos \beta= not \ possible$$

$$ h.) \ d(u,v)= ||u-v|| = ||(2,-5,4,6,-3)-(5,-2,1,-7,-4)||=||(-3,-3,3,13,1)||=$$
$$ \sqrt{(-3)^2+(-3)^2+3^2+13^2+1^2}= \sqrt{9+9+9+169+1}= \sqrt{197}$$

In [12]:
print("d(u,v): ", np.linalg.norm(u-v))

d(u,v):  14.035668847618199


$$i.) \ d(w,v)=not \ possible$$
$$j.) \ d(u,w)=not \ possible$$
$$k.) \ proj(u,v)= \frac{u.v}{||v||^2}.v= \frac{-6}{95}.\begin{bmatrix}5\\ -2 \\ 1 \\ -7 \\ -4 \end{bmatrix} =$$
$$(\frac{-6}{19}, \frac{12}{95}, \frac{-6}{95}, \frac{42}{95}, \frac{24}{95}) $$

In [15]:
print("proj(u,v): ", (u.dot(v)*v)/(np.linalg.norm(v)**2))

proj(u,v):  [-0.31578947  0.12631579 -0.06315789  0.44210526  0.25263158]


$$ l.) \ proj(w.v)=not \ possible$$
$$ m.) \ proj(u,w)=not \ possible $$

#### problem 4

$$ a.) \ u=(5,-7)$$
$$ ||u||= \sqrt{5^2+(-7)^2}= \sqrt{25+49}= \sqrt{74}$$
$$ u^T = \frac{l.u}{||u||}= \frac{l}{ \sqrt{74}}.\begin{bmatrix}5\\ -7 \end{bmatrix} = ( \frac{1}{5} , \frac{2}{5}, \frac{-2}{5}, \frac{4}{5}) $$

In [22]:
u = np.array([5,-7])
print("u': ", u/np.sqrt(u.dot(u)))

u':  [ 0.58123819 -0.81373347]


$$ b.) \ v=(1,2,-2,4)$$
$$ ||v|| = \sqrt{1^2+2^2+(-2)^2+4^2} = \sqrt{1+4+4+16} = \sqrt{25} = 5$$
$$ v^T = \frac{l.v}{||v||}= \frac{1}{5} . \begin{bmatrix}1 \\ 2 \\ -2 \\ 4 \end{bmatrix} = 
(\frac{1}{5} , \frac{2}{5}, \frac{-2}{5}, \frac{4}{5})$$

In [23]:
v = np.array([1,2,-2,4])
print("v': ", v/np.sqrt(v.dot(v)))

v':  [ 0.2  0.4 -0.4  0.8]


$$ c.) \ w=( \frac{1}{2} , \frac{-1}{3} , \frac{3}{4})$$
$$ ||w|| = \sqrt{ ( \frac{1}{2})^2 + ( \frac{-1}{3})^2 + ( \frac{3}{4})^2} = 
\sqrt{ \frac{1}{4} + \frac{1}{9} + \frac {9}{16}} = \sqrt{\frac{133}{144}} = \frac{ \sqrt{133}}{12}$$
$$ w^T = \frac{l.w}{||w||}= \frac{12}{ \sqrt{133}} . \begin{bmatrix} \frac{1}{2} \\ \frac{-1}{3} \\ \frac{3}{4} \end{bmatrix} = ( \frac{12}{2 \sqrt{133}}, \frac{-12}{3 \sqrt{133}}, \frac{36}{4 \sqrt{133}}) = ( \frac{6}{ \sqrt{133}}, \frac{-4}{ \sqrt {133}}, \frac{9}{ \sqrt{133}})$$

In [24]:
w = np.array([(1/2),(-1/3),(3/4)])
print("w': ", w/np.sqrt(w.dot(w)))

w':  [ 0.52026598 -0.34684399  0.78039897]


#### problem 5

$$ let \ u=(1,2,-2), \ v=(3,-12, 4), \ and \ a \ scalar \ k=-3$$

$$ ||u|| =  \sqrt{1^2+2^2+(-2)^2} = \sqrt{1+4+4} = \sqrt{9} = 3$$

In [25]:
u = np.array([1,2,-2])
v = np.array([3,-12,4])
k = -3
print("||u||: ", np.sqrt(u.dot(u)))

||u||:  3.0


$$ ||v|| = \sqrt{3^2+(12)^2+4^2} = \sqrt{9+144+16} = \sqrt{169} = 13$$

In [26]:
print("||v||: ", np.sqrt(v.dot(v)))

||v||:  13.0


$$ ||u+v|| = ||(1,2,-2)+(3,-12,4)||=||(4, -10,2)|| = \sqrt{4^2 + (-10)^2+2^2} = \sqrt{16+100+4} = \sqrt{120}$$

In [29]:
print("||u+v||: ", np.sqrt((u+v).dot((u+v))))

||u+v||:  10.954451150103322


$$ ||ku||=||-3 . (1,2,-2)||=||(-3,-6,6)||= \sqrt{(-3)^2 + (-60)^2+6^2} = \sqrt{9+36+36}=\sqrt{81}=9$$

In [28]:
print("||ku||: ", np.sqrt((k*u).dot((k*u))))

||ku||:  9.0


#### problem 6

$$ find \ k \ so \ that \ u \ and \ v \ are \ orthogonal$$
$$ a.) \ u=(3,k,-2), \ v=(6,-4,-3)  $$
$$ u.v= \begin{bmatrix} 3 \\ k \\ -2 \end{bmatrix} . \begin{bmatrix} 6 \\ -4 \\ -3 \end{bmatrix} = \begin{bmatrix} 18 \\ -4k \\6 \end{bmatrix} = 18-4k+6=0 $$
$$  18+6 =4k = 4k = 24 $$
$$ k=6$$

In [32]:
u = np.array([3,6,-2])
v = np.array([6,-4,-3])
if(u.dot(v) == 0):
    print("u.v: ", u.dot(v))

u.v:  0


$$ b.) u=(5,k,-4,2), \ v=(1,-3,2,2k)$$
$$ u.v= \begin{bmatrix} 5 \\ k \\ -4 \\ 2 \end{bmatrix} . \begin{bmatrix} 1 \\ -3 \\ 2 \\2k \end{bmatrix} = \begin{bmatrix} 5 \\ -3k \\ -8 \\ 4k 
\end{bmatrix} = 5-3k-8+4k = 0$$
$$ -3k+4k=8-5$$
$$ k=3 $$

In [33]:
u = np.array([5,3,-4, 2])
v = np.array([1,-3,2, 6])
if(u.dot(v) == 0):
    print("u.v: ", u.dot(v))

u.v:  0


$$ c.) \ u=(1,7,k+2,-2), \ v=(3,k,-3,k)$$
$$u.v = \begin{bmatrix} 1 \\ 7 \\ k+2 \\ -2 \end{bmatrix} . \begin{bmatrix} 3 \\ k \\ -3 \\ k \end{bmatrix} = \begin{bmatrix} 3 \\ 7k \\ -3k-6 \\ -2k \end{bmatrix} $$
$$ 3+7k-3k-6+2k=0$$
$$ 3-6+7k-3k-2k=0 $$
$$ -3+2k=0$$
$$ 2k = 3$$
$$ k = \frac{3}{2}$$

In [34]:
u = np.array([1,7,3.5, -2])
v = np.array([3,1.5,-3, 1.5])
if(u.dot(v) == 0):
    print("u.v: ", u.dot(v))

u.v:  0.0
