##### Tricia Jonina B. Alcisto

In [11]:
import numpy as np

def calculate_det(matrix):
    if not is_square(matrix):
        raise ValueError("Matrix must be square.")

    # Calculate determinant
    det_value = np.linalg.det(matrix)

    return det_value

def calculate_eigen(matrix):
    if not is_square(matrix):
        raise ValueError("Matrix must be square.")

    eigenvalues, eigenvectors = np.linalg.eig(matrix)

    return eigenvalues, eigenvectors

def is_square(matrix):
    return len(matrix.shape) == 2 and matrix.shape[0] == matrix.shape[1]

n = 4
random_matrix = np.random.rand(n, n)

det_value = calculate_det(random_matrix)
eigenvalues, eigenvectors = calculate_eigen(random_matrix)

print(f"Randomly Generated Matrix:\n{random_matrix}\n")
print(f"Det = {det_value}\n")
print(f"Eigenvalues:\n{eigenvalues}\n")
print(f"Eigenvectors:\n{eigenvectors}\n")


Randomly Generated Matrix:
[[0.11271058 0.45341772 0.95322566 0.44250424]
 [0.36696051 0.44050117 0.91948737 0.03866769]
 [0.50882511 0.76566865 0.38700106 0.31600392]
 [0.85434453 0.85003308 0.62316982 0.53240301]]

Det = 0.08934383295975584

Eigenvalues:
[ 2.03605278  0.26373753 -0.48194996 -0.34522454]

Eigenvectors:
[[ 0.46383355  0.32386077 -0.82607208 -0.82199932]
 [ 0.38029089 -0.52840193  0.04503735  0.33564622]
 [ 0.44687976 -0.06057463  0.26363569  0.02191004]
 [ 0.66372868  0.78245531  0.49605723  0.45954182]]

